Task 0

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,20 +1,23 @@
 #!/usr/bin/env bash
 
-if [ $# -lt 3 ]; then
-  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME [PATH_TO_SSH_KEY]"
+# Checking for command line arguments
+if [ $# -lt 4 ]; then
+  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
   exit 1
 fi
 
-file_path=$1
-server_ip=$2
+# Assigning parameters to variables
+path_to_file=$1
+ip=$2
 username=$3
-ssh_key=$4
+path_to_ssh_key=$4
 
-if [ -z "$ssh_key" ]; then
-  command="scp -o StrictHostKeyChecking=no \"$file_path\" \"$username@$server_ip:~/\""
+# Disabling strict host key checking
+scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
+
+# Checking if the transfer was successful
+if [ $? -eq 0 ]; then
+  echo "FILE WAS TRANSFERRED SUCCESSFULLY"
 else
-  command="scp -o StrictHostKeyChecking=no -i \"$ssh_key\" \"$file_path\" \"$username@$server_ip:~/\""
+  echo "FILE TRANSFER FAILED"
 fi
-
-eval "$command"
-
